/* Mongoose */
const path = require('path');
const mongoose = require('mongoose');

const { Schema } = mongoose;

const articleSchemeList = {
  provider: String,             // The provider with which the user authenticated (facebook, twitter, etc.).
  providerUserId: String,       // A unique identifier for the user, as generated by the service provider.
  displayName: String,          // The name of this user, suitable for display.
  name: {
    familyName: String,         // The family name of this user, or "last name" in most Western languages.
    givenName: String,          // The given name of this user, or "first name" in most Western languages.
    middleName: String,         // The middle name of this user.
  },
  emails: {
    value: String,              // The actual email address.
    type: String,               // The type of email address (home, work, etc.).
  },
  photos: {
    value: String,              // The URL of the image.
  },
  accessToken: String,
  userId: {
    type: String,
    ref: 'user',                // user id in table users
  },
  providerLog: Schema.Types.Mixed,
};

const articleScheme = new Schema(articleSchemeList, { timestamps: true });

const modelname = path.basename(__filename, '.js');
const model = mongoose.model(modelname, articleScheme);
module.exports = model;